In [1]:
import numpy as np

In [2]:
myarr = np.array([3,5,7,88,98,543], np.int8) #this is 1D array

In [3]:
myarr

array([ 3,  5,  7, 88, 98, 31], dtype=int8)

In [4]:
#memory managment is the key feature of the numpy. 
#If we use big number then will use the big memory space otherwise less memory space

In [5]:
#how to access the values inside the array if it's 1D

In [6]:
myarr[2]

7

In [7]:
#create 2D array

In [8]:
myarr_2d=np.array([[34,98,64,00,22,87,93,67,345]])

In [9]:
myarr_2d

array([[ 34,  98,  64,   0,  22,  87,  93,  67, 345]])

In [10]:
myarr_2d[0,6] =45

In [11]:
myarr_2d

array([[ 34,  98,  64,   0,  22,  87,  45,  67, 345]])

#There are five Method of Array Creation**

In [12]:
#Method Number 01: Using python (i.e list, dict etc)

In [13]:
#using list

In [14]:
listarr=np.array([[3,6,9],[2,4,8],[1,0,11]])

In [15]:
listarr

array([[ 3,  6,  9],
       [ 2,  4,  8],
       [ 1,  0, 11]])

In [16]:
listarr.dtype

dtype('int64')

In [17]:
listarr.shape

(3, 3)

In [18]:
listarr.size

9

In [19]:
#using dictionary 

In [20]:
np.array({34,33,23,56})

array({56, 33, 34, 23}, dtype=object)

In [21]:
#you can see the it's dtype is object if your doing the
#mathematical calculation then stay away from it.

In [22]:
zeros = np.zeros((5,8)) #Using the Function Zeros

In [23]:
zeros

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
rng = np.arange(555) #this function is ssimilar to range in python

In [25]:
rng

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [26]:
#linspace function

In [27]:
lspace = np.linspace(1,50,10)

In [28]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [29]:
#empty function in numpy array creation 

In [30]:
emp= np.empty((4,6))

In [31]:
emp

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [32]:
#empty_like returns the cpoy of the already existing array

In [33]:
em_like = np.empty_like(lspace)

In [34]:
em_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [35]:
ide = np.identity(45)

In [36]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [37]:
ide.shape

(45, 45)

In [38]:
#How to reshape the arrray

In [39]:
ava = np.arange(99)

In [40]:
ava

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [41]:
ava.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [42]:
#the imp point is the two in the reshape bracket must be equall to 99 
#after multiplying each other
#if the value are not equall to that then you can't reshape the array

In [43]:
ava = ava.ravel() #returns the 1 D array

In [44]:
ava

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [45]:
ava.shape

(99,)

In [46]:
x =[[1,2,3],[4,5,6],[7,1,0]]

In [47]:
ar= np.array(x)

In [48]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [49]:
ar.sum(axis=0) #sum of rows

array([12,  8,  9])

In [50]:
ar.sum(axis=1) #sum of column

array([ 6, 15,  8])

In [51]:
#hot to replace the rows with column which is called "transpose".

In [52]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [53]:
#ar.flat

In [54]:
for items in ar.flat:
    print(items)

1
2
3
4
5
6
7
1
0


In [55]:
for items in ar:
    print(items)

[1 2 3]
[4 5 6]
[7 1 0]


In [56]:
 ar.ndim

2

In [57]:
ar.size

9

In [58]:
ar.nbytes

72

In [59]:
one = np.array([1,4,6,8,9,4,3,34,675])

In [60]:
one.argmax()

8

In [62]:
ar.argmax(axis=0)

array([2, 1, 1])

In [64]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [65]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [66]:
ar2 = np.array([[1,2,1],[4,0,6],[8,1,0]])

In [67]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [68]:
#adding the matrics

In [69]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [70]:
#you can't do the same thing in the python list

In [71]:
#multiplying matrics
ar *ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [72]:
#Taking Square root in numpy
np.sqrt(ar2)

array([[1.        , 1.41421356, 1.        ],
       [2.        , 0.        , 2.44948974],
       [2.82842712, 1.        , 0.        ]])

In [74]:
 np.where(ar>5)
#the element index where the value is less then 5 
#it return the tuple 
type(np.where(ar>5))

tuple

In [76]:
np.count_nonzero(ar)

8

In [79]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [ ]:
#in the start we said that numpy take less space then pytho, let's see how.

In [80]:
import sys

In [84]:
py_ar= [0,44,3,2]

In [85]:
np_ar= np.array(py_ar)

In [86]:
sys.getsizeof(1) * len(py_ar)

112

In [89]:
np_ar.itemsize * np_ar.size

32